import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { JsonLd } from "@/components/json-ld";
import { VerifiedValue } from "@/components/verified-value";
import { productBySlug, products } from "@/data/products";
import { conditionBySlug, conditions } from "@/data/conditions";
import { absoluteUrl } from "@/lib/site";
import type { WaterFountainProduct } from "@/types/product";

export const dynamicParams=false;
export function generateStaticParams(){return [...products.map(({slug})=>({slug})),...conditions.map(({slug})=>({slug}))]}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const product=productBySlug(slug);const condition=conditionBySlug(slug);if(product)return{title:`${product.productName}（${product.model}）の仕様`,description:`${product.productName}の容量、電源、材質、お手入れ、確認日と一次情報。`,alternates:{canonical:`/water-fountains/${slug}`},openGraph:{url:`/water-fountains/${slug}`,title:`${product.productName}の確認済み仕様`}};if(condition)return{title:`循環式給水器：${condition.title}`,description:condition.summary,alternates:{canonical:`/water-fountains/${slug}`},robots:condition.status==="preparing"?{index:false,follow:true}:undefined,openGraph:{url:`/water-fountains/${slug}`,title:condition.title}};return{}}
const fields:{label:string;key:keyof WaterFountainProduct;format?:(value:never)=>string}[]=[{label:"容量",key:"capacityLiters",format:(v)=>`${v}L`},{label:"対象動物",key:"targetPets"},{label:"材質",key:"material"},{label:"給電方式",key:"powerMethod"},{label:"完全コードレス",key:"cordless"},{label:"ポンプ方式",key:"pumpMethod"},{label:"静音仕様",key:"quietSpecification"},{label:"フィルター",key:"filter"},{label:"交換目安",key:"filterReplacement"},{label:"洗浄可能部品",key:"washableParts"},{label:"食洗機対応",key:"dishwasherSafe"},{label:"サイズ",key:"dimensions"},{label:"重量",key:"weight"},{label:"アプリ対応",key:"appSupport"},{label:"飲水記録",key:"drinkingLog"},{label:"水位通知",key:"waterLevelNotification"},{label:"電源断時",key:"powerFailureBehavior"}];

export default async function SlugPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const product=productBySlug(slug);if(product)return <ProductDetail product={product}/>;const condition=conditionBySlug(slug);if(condition){const matches=condition.productSlugs.map(productBySlug).filter((item):item is WaterFountainProduct=>Boolean(item));return <main><section className="page-hero"><div className="container"><p className="eyebrow">CONDITION · {condition.status==="active"?"SPEC VERIFIED":"PREPARING"}</p><h1>{condition.title}の循環式給水器</h1><p className="lede">{condition.summary}</p></div></section><section className="section"><div className="container"><div className="panel"><h2>判定基準</h2><p>{condition.criterion}</p>{condition.status==="preparing"&&<p className="notice">評価準備中です。根拠が揃うまでランキングや適合商品の断定は行いません。</p>}<ul>{condition.notes.map(note=><li key={note}>{note}</li>)}</ul></div>{matches.length>0&&<div className="product-grid">{matches.map(item=><article className="product-card" key={item.slug}><p className="maker">{item.manufacturer}</p><h3><Link href={`/water-fountains/${item.slug}`}>{item.productName}</Link></h3><p className="model">{item.model}</p><p>公開仕様が上記基準に該当します。使用感の推薦ではありません。</p></article>)}</div>}</div></section></main>}notFound()}

function ProductDetail({product}:{product:WaterFountainProduct}){const productJson={"@context":"https://schema.org","@type":"Product",name:product.productName,brand:{"@type":"Brand",name:product.manufacturer},manufacturer:{"@type":"Organization",name:product.manufacturer},model:product.model,url:absoluteUrl(`/water-fountains/${product.slug}`)};return <main><JsonLd data={productJson}/><JsonLd data={{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"給水器一覧",item:absoluteUrl("/water-fountains")},{"@type":"ListItem",position:2,name:product.productName,item:absoluteUrl(`/water-fountains/${product.slug}`)}]}}/><div className="container breadcrumbs"><Link href="/water-fountains">給水器一覧</Link> / {product.model}</div><section className="page-hero"><div className="container"><p className="eyebrow">{product.manufacturer}</p><h1>{product.productName}</h1><p className="model">{product.model} · 仕様確認日 {product.checkedAt}</p></div></section><section className="section"><div className="container detail-grid"><div><h2>基本仕様</h2><dl className="spec-list">{fields.map(field=><div key={field.key}><dt>{field.label}</dt><dd><VerifiedValue field={product[field.key] as never} format={field.format} showSources/></dd></div>)}</dl><h2>仕様評価と編集者評価</h2><div className="three-grid"><div className="panel"><h3>仕様評価</h3><p>一次情報から確認できる値だけを表示しています。総合点は付けません。</p></div><div className="panel"><h3>編集者評価</h3><p className="unknown status">実機評価は未実施</p><p>動作音、洗いやすさ、アプリ操作性は評価していません。</p></div></div><h2>安全上の注意</h2><ul className="warning-list">{product.safetyNotes.map(note=><li key={note}>{note}</li>)}</ul></div><aside className="sidebar"><div className="safe-commerce"><strong>販売先を確認中</strong><p>ASIN・正規販売者・affiliate設定が未確認のため、購入ボタンは表示しません。</p></div><div className="panel"><h3>参考価格</h3><p>{product.referencePrice?.label??"未確認"}</p><p className="subtle">確認日 {product.referencePrice?.checkedAt??product.checkedAt}。価格・在庫は変動します。</p><a href={product.officialUrl} rel="noopener noreferrer">メーカー公式情報を確認</a></div></aside></div></section></main>}
