import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { JsonLd } from "@/components/json-ld";
import { waterGuideBySlug, waterGuides } from "@/data/guides";
import { absoluteUrl, OPEN_GRAPH_IMAGE } from "@/lib/site";

export const dynamicParams = false;
export function generateStaticParams() { return waterGuides.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const guide = waterGuideBySlug((await params).slug); return guide ? { title: guide.title, description: guide.description, alternates: { canonical: `/water-fountains/guides/${guide.slug}` }, openGraph: { url: `/water-fountains/guides/${guide.slug}`, title: guide.title, description: guide.description, images: [OPEN_GRAPH_IMAGE] } } : {}; }
export default async function GuidePage({ params }: { params: Promise<{ slug: string }> }) { const guide = waterGuideBySlug((await params).slug); if (!guide) notFound(); const path = `/water-fountains/guides/${guide.slug}`; return <main><JsonLd data={{ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "トップ", item: absoluteUrl("/") }, { "@type": "ListItem", position: 2, name: "循環式ペット給水器", item: absoluteUrl("/water-fountains") }, { "@type": "ListItem", position: 3, name: "ガイド", item: absoluteUrl("/water-fountains/guides") }, { "@type": "ListItem", position: 4, name: guide.title, item: absoluteUrl(path) }] }} /><section className="page-hero"><div className="narrow"><p className="eyebrow">CARE & BUYING GUIDE</p><h1>{guide.title}</h1><p className="lede">{guide.answer}</p></div></section><article className="section narrow rich"><nav aria-label="パンくず"><Link href="/">トップ</Link> / <Link href="/water-fountains">給水器</Link> / <Link href="/water-fountains/guides">ガイド</Link></nav><div className="notice"><strong>結論</strong><p>{guide.conclusion}</p></div>{guide.sections.map((section) => <section key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets ? <ul>{section.bullets.map((item) => <li key={item}>{item}</li>)}</ul> : null}{section.table ? <div className="table-scroll"><table className="compare-table"><thead><tr>{section.table.headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{section.table.rows.map((row) => <tr key={row.join("|")}>{row.map((cell, index) => index === 0 ? <th key={cell}>{cell}</th> : <td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div> : null}</section>)}<section><h2>関連する比較・商品情報</h2><div className="condition-grid">{guide.relatedLinks.map((link) => <Link className="condition-card" href={link.href} key={link.href}><h3>{link.label}</h3><p>{link.note}</p><span>確認する →</span></Link>)}</div></section><p className="notice">公開仕様は変更される場合があります。購入前にメーカー公式ページと取扱説明書で最新情報を確認してください。</p></article></main>; }
